# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: update-submodule

# The type of the application to build.
type: "nodejs:18"

web:
  commands:
    start: |
      sleep infinity

source:
  operations:
    rebuild_root:
      command: |
        echo "before submodule update"
        set -e
        git submodule update --init --recursive
        git submodule update --remote --checkout
        echo "after submodule update"
        git add admin api gatsby mercure
        git commit -m "Updating submodules admin, api, gatsby and mercure"
