source:
  operations:
    rebuild_root:
      command: |
        echo "before submodule update"
        set -e
        git submodule update --init --recursive
        git submodule update --remote --checkout
        echo "after submodule update"
        git add admin api gatsby mercure
        git commit -m "Updating submodules admin, api, gatsby and mercure"
