# Complete list of all available properties: https://docs.platform.sh/create-apps/app-reference.html

# A unique name for the app. Must be lowercase alphanumeric characters. Changing the name destroys data associated
# with the app.
api:
  # The runtime the application uses.
  # Complete list of available runtimes: https://docs.platform.sh/create-apps/app-reference.html#types
  type: php:8.2

  # The relationships of the application with services or other applications.
  # The left-hand side is the name of the relationship as it will be exposed
  # to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
  # side is in the form `<service name>:<endpoint name>`.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#relationships
  relationships:
    database: "database:postgresql"

  # The size of the persistent disk of the application (in MB). Minimum value is 128.
  disk: 2048

  # Mounts define directories that are writable after the build is complete. If set as a local source, disk property is required.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#mounts
  mounts:
    "/var/cache": "shared:files/cache"
    "/var/log": "shared:files/log"
    "/var/sessions": "shared:files/sessions"

  # The web key configures the web server running in front of your app.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#web
  web:
    # Each key in locations is a path on your site with a leading /.
    # More information: https://docs.platform.sh/create-apps/app-reference.html#locations
    locations:
      "/":
        # The directory to serve static assets for this location relative to the app’s root directory. Must be an
        # actual directory inside the root directory.
        root: "public"
        # Whether to forward disallowed and missing resources from this location to the app. A string is a path
        # with a leading / to the controller, such as /index.php.
        passthru: '/index.php'
        # Files to consider when serving a request for a directory.
        index:
          - index.php
        # Whether to allow scripts to run. Doesn’t apply to paths specified in passthru. Meaningful only on PHP containers.
        scripts: true
        # Whether to allow serving files which don’t match a rule.
        allow: true
        headers:
          Access-Control-Allow-Origin: "*"

  # Variables to control the environment. More information: https://docs.platform.sh/create-apps/app-reference.html#variables
  variables:
    env:
      APP_ENV: 'prod'
    php:
      assert.active: off

  # Specifies a default set of build tasks to run. Flavors are language-specific.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#build
  build:
    flavor: composer

  # Installs global dependencies as part of the build process. They’re independent of your app’s dependencies and
  # are available in the PATH during the build process and in the runtime environment. They’re installed before
  # the build hook runs using a package manager for the language.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#dependencies
  dependencies:
    php:
      composer/composer: "^2"

  # Hooks allow you to customize your code/environment as the project moves through the build and deploy stages
  # More information: https://docs.platform.sh/create-apps/app-reference.html#hooks
  hooks:
    # The build hook is run after any build flavor.
    # More information: https://docs.platform.sh/create-apps/hooks/hooks-comparison.html#build-hook
    build: |
      set -x -e
      
      curl -s https://get.symfony.com/cloud/configurator | bash
      symfony-build

    # The deploy hook is run after the app container has been started, but before it has started accepting requests.
    # More information: https://docs.platform.sh/create-apps/hooks/hooks-comparison.html#deploy-hook
    deploy: |
      set -x -e
      
      symfony-deploy

  # Scheduled tasks for the app.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#crons
  crons:
    update-sighting:
      spec: '*/5 * * * *'
      cmd: './bin/console app:update-sighting-scores'

  # Customizations to your PHP or Lisp runtime. More information: https://docs.platform.sh/create-apps/app-reference.html#runtime
  runtime:
    extensions:
      - ctype
      - iconv
      - apcu
      - mbstring
      - sodium
      - xsl
      - pdo_pgsql

  # Information on the app's source code and operations that can be run on it.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#source
  source:
    # The path where the app code lives. Defaults to the directory of the .platform.app.yaml file. Useful for multi-app setups.
    root: api

admin:
  type: nodejs:16

  # How many resources to devote to the app. Defaults to AUTO in production environments.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#sizes
  size: L

  # Fine-tune allocated resources
  # https://docs.platform.sh/create-apps/flexible-resources.html#performance-profiles
  resources:
    base_memory: 1024
    memory_ratio: 1024

  # The size of the persistent disk of the application (in MB). Minimum value is 128.
  disk: 1024

  # Mounts define directories that are writable after the build is complete. If set as a local source, disk property is required.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#mounts
  mounts:
    '/.tmp_platformsh': 'shared:files/tmp_platformsh'
    '/build': 'shared:files/build'
    '/.cache': 'shared:files/.cache'
    '/node_modules/.cache': 'shared:files/node_modules/.cache'

  # The web key configures the web server running in front of your app.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#web
  web:
    # Each key in locations is a path on your site with a leading /.
    # More information: https://docs.platform.sh/create-apps/app-reference.html#locations
    locations:
      "/admin":
        # The directory to serve static assets for this location relative to the app’s root directory. Must be an
        # actual directory inside the root directory.
        root: "build"
        # Whether to forward disallowed and missing resources from this location to the app. A string is a path
        # with a leading / to the controller, such as /index.php.
        passthru: "/admin/index.html"
        # Files to consider when serving a request for a directory.
        index:
          - "index.html"
        # The number of seconds whitelisted (static) content should be cached.
        expires: 300s
        # Whether to allow scripts to run. Doesn’t apply to paths specified in passthru. Meaningful only on PHP containers.
        scripts: true
        # Whether to allow serving files which don’t match a rule.
        allow: true
        # The key of each item in rules is a regular expression to match paths exactly. If an incoming request
        # matches the rule, it’s handled by the properties under the rule, overriding any conflicting rules from the
        # rest of the locations properties.
        # More information: https://docs.platform.sh/create-apps/app-reference.html#rules
        rules:
          \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|html|ico|svg?)$:
            allow: true
          ^/admin/robots\.txt$:
            allow: true
          ^/admin/manifest\.json$:
            allow: true
          ^/admin/_next:
            allow: true
          ^/admin/sitemap:
            allow: true
        headers:
          Access-Control-Allow-Origin: "*"

  # Variables to control the environment. More information: https://docs.platform.sh/create-apps/app-reference.html#variables
  variables:
    env:
      NODE_OPTIONS: '--max-old-space-size=1536'

  # Specifies a default set of build tasks to run. Flavors are language-specific.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#build
  build:
    flavor: none

  # Hooks allow you to customize your code/environment as the project moves through the build and deploy stages
  # More information: https://docs.platform.sh/create-apps/app-reference.html#hooks
  hooks:
    # The build hook is run after any build flavor.
    # More information: https://docs.platform.sh/create-apps/hooks/hooks-comparison.html#build-hook
    build: |
      set -eu
      corepack yarn install --immutable --force
    # The post_deploy hook is run after the app container has been started and after it has started accepting requests.
    # More information: https://docs.platform.sh/create-apps/hooks/hooks-comparison.html#deploy-hook
    post_deploy: |
      corepack yarn run build
  # Information on the app's source code and operations that can be run on it.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#source
  source:
    # The path where the app code lives. Defaults to the directory of the .platform.app.yaml file. Useful for multi-app setups.
    root: admin

gatsby:
  # Complete list of all available properties: https://docs.platform.sh/create-apps/app-reference.html

  # A unique name for the app. Must be lowercase alphanumeric characters. Changing the name destroys data associated
  # with the app.

  # The runtime the application uses.
  # Complete list of available runtimes: https://docs.platform.sh/create-apps/app-reference.html#types
  type: 'nodejs:18'

  # How many resources to devote to the app. Defaults to AUTO in production environments.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#sizes
  size: L

  # Fine-tune allocated resources
  # https://docs.platform.sh/create-apps/flexible-resources.html#performance-profiles
  resources:
    base_memory: 1024
    memory_ratio: 1024

  # The size of the persistent disk of the application (in MB). Minimum value is 128.
  disk: 1536

  # Mounts define directories that are writable after the build is complete. If set as a local source, disk property is required.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#mounts
  mounts:
    '/.cache':
      source: local
      source_path: cache
    '/.config':
      source: local
      source_path: config
    '/public':
      source: local
      source_path: public

  # The web key configures the web server running in front of your app.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#web
  web:
    # Each key in locations is a path on your site with a leading /.
    # More information: https://docs.platform.sh/create-apps/app-reference.html#locations
    locations:
      '/site':
        # The directory to serve static assets for this location relative to the app’s root directory. Must be an
        # actual directory inside the root directory.
        root: 'public'
        # Files to consider when serving a request for a directory.
        index: [ 'index.html' ]
        # Whether to allow scripts to run. Doesn’t apply to paths specified in passthru. Meaningful only on PHP containers.
        scripts: false
        # Whether to allow serving files which don’t match a rule.
        allow: true

  # Variables to control the environment. More information: https://docs.platform.sh/create-apps/app-reference.html#variables
  variables:
    env:
      NODE_OPTIONS: --max-old-space-size=1536

  # Specifies a default set of build tasks to run. Flavors are language-specific.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#build
  build:
    flavor: none

  # Installs global dependencies as part of the build process. They’re independent of your app’s dependencies and
  # are available in the PATH during the build process and in the runtime environment. They’re installed before
  # the build hook runs using a package manager for the language.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#dependencies
  dependencies:
    nodejs:
      yarn: "1.22.17"

  # Hooks allow you to customize your code/environment as the project moves through the build and deploy stages
  # More information: https://docs.platform.sh/create-apps/app-reference.html#hooks
  hooks:
    # The build hook is run after any build flavor.
    # More information: https://docs.platform.sh/create-apps/hooks/hooks-comparison.html#build-hook
    build: |
      set -e
      yarn --frozen-lockfile
    # The post_deploy hook is run after the app container has been started and after it has started accepting requests.
    # More information: https://docs.platform.sh/create-apps/hooks/hooks-comparison.html#deploy-hook
    post_deploy: |
      yarn build --prefix-paths

  # Information on the app's source code and operations that can be run on it.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#source
  source:
    # The path where the app code lives. Defaults to the directory of the .platform.app.yaml file. Useful for multi-app setups.
    root: gatsby

mercure:
  # Complete list of all available properties: https://docs.platform.sh/create-apps/app-reference.html

  # A unique name for the app. Must be lowercase alphanumeric characters. Changing the name destroys data associated
  # with the app.

  # The runtime the application uses.
  # Complete list of available runtimes: https://docs.platform.sh/create-apps/app-reference.html#types
  type: golang:1.18

  # How many resources to devote to the app. Defaults to AUTO in production environments.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#sizes
  size: L

  # The size of the persistent disk of the application (in MB). Minimum value is 128.
  disk: 2048

  # Mounts define directories that are writable after the build is complete. If set as a local source, disk property is required.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#mounts
  mounts:
    "database": { source: local, source_path: "database" }
    "/.local": { source: local, source_path: .local }
    "/.config": { source: local, source_path: .config }

  # The web key configures the web server running in front of your app.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#web
  web:
    # Commands are run once after deployment to start the application process.
    # More information: https://docs.platform.sh/create-apps/app-reference.html#web-commands
    commands:
      # The command to launch your app. If it terminates, it’s restarted immediately.
      start: ./mercure run --config Caddyfile.platform_sh
    # Each key in locations is a path on your site with a leading /.
    # More information: https://docs.platform.sh/create-apps/app-reference.html#locations
    locations:
      /:
        # Whether to forward disallowed and missing resources from this location to the app. A string is a path
        # with a leading / to the controller, such as /index.php.
        passthru: true
        # Whether to allow scripts to run. Doesn’t apply to paths specified in passthru. Meaningful only on PHP containers.
        scripts: false
        # Whether to allow serving files which don’t match a rule.
        allow: true
        request_buffering:
          enabled: false
        headers:
          Access-Control-Allow-Origin: "*"

  # Variables to control the environment. More information: https://docs.platform.sh/create-apps/app-reference.html#variables
  variables:
    env:
      MERCUREVERSION: 0.14.4
      SERVER_NAME: ":8888"
      MERCURE_TRANSPORT_URL: "bolt:///var/run/mercure.db?size=1000&cleanup_frequency=0.5"
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origin *
        publish_origins *
        subscriptions
        demo
      GLOBAL_OPTIONS: |
        auto_https off
      MERCURE_PUBLISHER_JWT_KEY: "!ChangeThisMercureHubJWTSecretKey!"
      MERCURE_SUBSCRIBER_JWT_KEY: "!ChangeThisMercureHubJWTSecretKey!"

  # Specifies a default set of build tasks to run. Flavors are language-specific.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#build
  build:
    flavor: none

  # Hooks allow you to customize your code/environment as the project moves through the build and deploy stages
  # More information: https://docs.platform.sh/create-apps/app-reference.html#hooks
  hooks:
    # The build hook is run after any build flavor.
    # More information: https://docs.platform.sh/create-apps/hooks/hooks-comparison.html#build-hook
    build: |
      # Install Mercure using cache
      echo "${MERCUREVERSION}"
      FILE="mercure_${MERCUREVERSION}_Linux_x86_64.tar.gz"
      if [ ! -f "$PLATFORM_CACHE_DIR/$FILE" ]; then
        URL="https://github.com/dunglas/mercure/releases/download/v${MERCUREVERSION}/$FILE"
        echo "Downloading $URL"
        wget -O "$PLATFORM_CACHE_DIR/$FILE" $URL
      else
        echo "Found $FILE in cache, using cache"
      fi
      file $PLATFORM_CACHE_DIR/$FILE
      tar xvzf $PLATFORM_CACHE_DIR/$FILE

  # Information on the app's source code and operations that can be run on it.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#source
  source:
    # The path where the app code lives. Defaults to the directory of the .platform.app.yaml file. Useful for multi-app setups.
    root: mercure/.config

# The name of this app. Must be unique within a project.
update-submodule:
  # The type of the application to build.
  type: "nodejs:18"

  # The web key configures the web server running in front of your app.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#web
  web:
    # Commands are run once after deployment to start the application process.
    # More information: https://docs.platform.sh/create-apps/app-reference.html#web-commands
    commands:
      # The command to launch your app. If it terminates, it’s restarted immediately.
      start: |
        sleep infinity
  # Information on the app's source code and operations that can be run on it.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#source
  source:
    ######################################################################################################################
    ##                                                                                                                  ##
    ## This source operation is part of the Platform.sh process of updating and maintaining our collection of           ##
    ## templates. For more information see https://docs.platform.sh/create-apps/source-operations.html and              ##
    ## https://github.com/platformsh/source-operations                                                                  ##
    ##                                                                                                                  ##
    ##                  YOU CAN SAFELY DELETE THIS COMMENT AND THE LINES BENEATH IT                                     ##
    ##                                                                                                                  ##
    ######################################################################################################################
    operations:
      rebuild:
        command: |
          git submodule update --init --recursive
          git submodule update --remote --checkout
          git add admin api gatsby mercure
          git commit -m "Updating submodules admin, api, gatsby and mercure"