# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.
# More information: https://docs.platform.sh/define-routes.html
https://{default}:
  type: upstream
  upstream: "app:http"
  id: app

https://{default}/admin:
  type: upstream
  # the first part should be your project name
  upstream: admin:http
  ssi:
    enabled: false
  cache:
    cookies:
    - '*'
    default_ttl: 0
    enabled: true
    headers:
    - Accept
    - Accept-Language
  id: admin

https://{default}/site:
  type: upstream
  upstream: "gatsby:http"
  id: gatsby

https://mercure.{default}:
  type: upstream
  upstream: "mercure:http"
  cache:
    enabled: false
  id: mercure
